spring.application.name=spring-api-gateway

# On pointe vers le Config Server
spring.config.import=optional:configserver:http://localhost:8888
spring.cloud.config.enabled=true

spring.cloud.config.profile=dev

# Mapping des variables (sera rempli par le Config Server)
server.port=${gateway.port}

#Configuration des routes via variables pour identity-service
#spring.cloud.gateway.routes[0].id=identity-service
#spring.cloud.gateway.routes[0].uri=lb://identity-service
#spring.cloud.gateway.routes[0].predicates[0]=Path=${gateway.identity-path}

#Configuration des routes via variables pour project-service
#spring.cloud.gateway.routes[1].id=project-service
#spring.cloud.gateway.routes[1].uri=lb://project-service
#spring.cloud.gateway.routes[1].predicates[0]=Path=${gateway.project-path}


# Connexion à Eureka via variable
eureka.client.service-url.defaultZone=${gateway.urlregistry}

# JWT
identity-service.jwt-secret=CIS_Integration_2026_Secure_Key_For_Identity_Service_ESMT_Dakar_Senegal
identity-service.jwt-expiration=86400000




